### PR TITLE
Major revision, first half.  Work in progress.

### PR DESCRIPTION
**Pull request by rkdarst**
This is my first attempt at improvements.  It isn't ready to be merged.

- I've mostly focused on the first half so far.  The same basic structure is there, but some rearrangement, some moved towards the end, more commentary.
- There are misc TODOs and editor's notes around (to be acted on and removed).  Also I have used comments for speaker notes, something should be done with them sometime I guess.

I think the first half is a good introduction to why licenses are important and what the main concepts are.  The second half is a lot of assorted topics.  We should think about how it will end.  I would propose after the cake example, have an intermediate wrap-up making a clear case for open licensing and reproducible research.  Then, second half is assorted instructions/suggestions which can be presented in more or less detail depending on the audience.  However, we should enough workflow/instructions before the break so that the talk's outcomes are actionable.

(above is also notes/random thoughts for me for the next few days)  What do you think?

### CODE REVIEW

**Comment by bast** [comment]
Thanks Richard! I like the changes and clarifications but please also add you as co-author. Actionable outcomes would be great. Also feel free to cut content. One thing that was not well explained in my version are license agreements and copyright transferals. Also they might scare people away from contributing.

**Comment by rkdarst** [comment]
Feel free to merge, I think it is also set so that you can push to my
branch. Hopefully I can get to finishing my stuff tomorrow, but by all
means start already.

My plan now is before midpoint conclusion, talk about the practical stuff,
starting project, contributing to existisg project, etc.

- Richard

**Comment by bast** [comment]
OK but I also don't want to make you work on the weekend. I will present this coming Thursday so there is still time.

**Comment by bast** [comment]
Thank you! I will merge it and make a pass on it myself. Thank you very much for the work!

**Comment by rkdarst** [comment]
Great, thanks.  I didn't have time to get to it, but I can make another pass (sometime) after your revisions.

**Comment by bast** [comment]
Thank you. Do you mind if I add you as co-author?

**Pull request merged**
