### PR TITLE
Lund2018

### PR DESCRIPTION
**Pull request by Sabryr**
Some suggested changes for Lund

### CODE REVIEW

**Comment by bast** [comment]
Preview: http://cicero.xyz/v2/remark/github/coderefinery/software-licensing/lund2018/talk.md/

**Comment by bast** [comment]
Thank you for your work! Few suggestions:
- title slide contains unnecessary brackets, please see preview, I think it is OK if affiliations are not links but normal text
- copyright/copyleft image is huge and pushes the text too much to the bottom
- please move at least one slide discussion derivative work in the scientific context from bonus material to main talk, this was cut short last time
- please don't kill the slide with the famous restaurant and github :-) but you are free to do so but then let's keep this on a branch and branch off

**Comment by bast** [comment]
What you can also do is to present directly from this branch (then adjust link on workshop page) and I can transfer almost all changes but I really want to keep the cake example, with the restaurant. I think this really works well. But you don't have to use that material on the branch.

**Comment by Sabryr** [comment]
"famous restaurant and github" I like that one, removed as not sure where to fit it

**Comment by bast** [comment]
And it's fine to remove for your talk but on master I prefer to keep it in the place where it is.

**Pull request closed without merging**
