### PR TITLE
Change the GPL to  shackles

### PR DESCRIPTION
**Pull request by Sabryr**
Suggestion by Jyry included

### CODE REVIEW

**Comment by bast** [comment]
Can you please give a link to the slide which contains new material? (in the address bar replace master by your branch) This makes it easier to review.

**Comment by Sabryr** [comment]
Slide 15

**Comment by bast** [comment]
What I wanted is this :-)
http://cicero.xyz/v2/remark/github/coderefinery/software-licensing/image_edits/talk.md/#15

**Comment by bast** [comment]
But why is GPL a shackle weight ball?

**Comment by bast** [comment]
OK - but my question holds: why? :-) Does GPL imprison codes?

**Comment by bast** [comment]
So what exactly happened in this PR?

**Comment by Sabryr** [comment]
Jyry and me used the same image to convey different things. I used it to tell the story of Ubuntu in Asia (when it arrived people did not know what to expect from free as they were costumed to using pirate copies of OS),. Jyry was using it to tell (I guess) why something given away without license may have strings attached.  I am changing back the image to previous version as I will tell about Ubuntu in Oslo. On a different note, this image switch is a good example of using Version control and using SVG for images in Git.

**Comment by bast** [comment]
SVG is awesome. Sorry my question was not clear: does this PR contain more than changing an image and then changing in back? Because if no, then it is not clear to me why we should not simply close it. But if it contains more than we want to merge it. So my question: does it contain more?

**Comment by Sabryr** [comment]
Yes it is only the image. I see, the confusion is may be due to the fact that I had pushed to the same  branch which I had pull-requested before.

**Comment by bast** [comment]
So overall nothing changed and we can close this PR without merging?

**Pull request merged**
